version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: bayhan
      POSTGRES_PASSWORD: bayhanpass
      POSTGRES_DB: bayhan_db
    ports:
      - "5432:5432"
    volumes:
      - ./backend/prisma/data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: yarn dev
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://bayhan:bayhanpass@db:5432/bayhan_db
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: yarn start
    ports:
      - "3000:3000"
    depends_on:
      - backend